# Generated by Django 2.1.3 on 2018-11-17 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_update', models.DateTimeField(auto_now=True)),
                ('ts_beg', models.DateTimeField(help_text='The date of the account activation')),
                ('ts_end', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
